camera_info:
  image_width: 800
  image_height: 600
stop_line_positions:
    - [1148.56, 1184.65]
    - [1559.2, 1158.43]
    - [2122.14, 1526.79]
    - [2175.237, 1795.71]
    - [1493.29, 2947.67]
    - [821.96, 2905.8]
    - [161.76, 2303.82]
    - [351.84, 1574.65]
tl:
  tl_classification_model: 'models/tl_weights_classifier_sim.h5'
  tl_detection_model: 'models/tl_weights_detector_sim.h5'
  tl_detector_model_json: 'models/tl_model_detector_sim.json'
  classifier_resize_height: 64
  classifier_resize_width: 32
  detector_resize_width: 128
  detector_resize_height: 96
  projection_threshold: 2
  projection_min: 200
  detector_rate: 6
  is_carla: false
  color_mode: 'rgb8'